name: SpigotMiscellanea
author: kccricket
main: net.kccricket.spigotmiscellanea.MiscellaneaPlugin
website: https://kccricket.net
description: Miscellanea plugin developed by kccricket
version: 1.0.0
api-version: 1.20
softdepend: [NametagEdit]
